import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Tauri serves the static files generated by `next build` from the `out/`
  // directory. Server-only features (SSR, route handlers with a runtime,
  // cache components) are not available in a desktop app, so the whole app is
  // exported as a static site and hydrated on the client.
  output: "export",

  // `next/image` optimization requires a server. Disable it so images are
  // served as-is from the bundle.
  images: {
    unoptimized: true,
  },

  // Emit `/route/index.html` instead of `/route.html` so the file layout also
  // works when the assets are opened through a custom protocol handler.
  trailingSlash: true,

  turbopack: {
    rules: {
      "*.css": {
        loaders: ["@tailwindcss/turbopack"],
        as: "*.css",
      },
    },
  },
};

export default nextConfig;
